export const stats = [
    "# to maximum Mana",
    "# to maximum Life",
    "#% to Cold Resistance",
    "#% to Fire Resistance",
    "#% to Lightning Resistance",
    "#% increased Rarity of Items found",
    "# to Intelligence",
    "# to Dexterity",
    "# to Strength",
    "# Life Regeneration per second",
    "# to Accuracy Rating",
    "#% increased Mana Regeneration Rate",
    "#% increased Spell Damage",
    "# to maximum Energy Shield",
    "Gain # Mana per Enemy Killed",
    "Gain # Life per Enemy Killed",
    "# to Stun Threshold",
    "#% increased Energy Shield",
    "Adds # to # Physical Damage to Attacks",
    "#% increased Cast Speed",
    "#% increased Attribute Requirements",
    "#% increased Physical Damage",
    "# to Accuracy Rating",
    "# to Evasion Rating",
    "#% increased Movement Speed",
    "# to Spirit",
    "#% increased Evasion Rating",
    "#% to Chaos Resistance",
    "# to Armour",
    "#% to all Elemental Resistances",
    "#% increased Light Radius",
    "#% increased maximum Energy Shield",
    "#% increased Armour",
    "Adds # to # Physical Damage",
    "Adds # to # Cold damage to Attacks",
    "Adds # to # Lightning damage to Attacks",
    "#% increased Lightning Damage",
    "# to Evasion Rating",
    "Adds # to # Lightning Damage",
    "Adds # to # Fire damage to Attacks",
    "# to # Physical Thorns damage",
    "# to maximum Energy Shield",
    "#% increased Evasion Rating",
    "#% increased Cold Damage",
    "#% increased Evasion and Energy Shield",
    "#% increased Armour and Evasion",
    "#% increased Armour and Energy Shield",
    "# to all Attributes",
    "#% increased Armour",
    "Adds # to # Fire Damage",
    "#% increased Fire Damage",
    "#% increased Critical Hit Chance",
    "Adds # to # Cold Damage",
    "#% increased Attack Speed",
    "#% increased Rarity of Items found in this Area",
    "#% increased Chaos Damage",
    "#% increased Magic Monsters",
    "#% increased number of Rare Monsters",
    "#% increased Critical Damage Bonus",
    "#% increased Critical Hit Chance for Spells",
    "# to Level of all Projectile Skills",
    "#% increased Attack Speed",
    "# to Level of all Melee Skills",
    "#% increased chance to Ignite",
    "#% to Critical Hit Chance",
    "# to Level of all Minion Skills",
    "#% increased Critical Spell Damage Bonus",
    "# to Armour",
    "#% to Critical Damage Bonus",
    "#% increased Elemental Damage with Attacks",
    "#% increased Gold found in this Area",
    "Leech #% of Physical Attack Damage as Life",
    "Leech #% of Physical Attack Damage as Mana",
    "Leeches #% of Physical Damage as Mana",
    "Leeches #% of Physical Damage as Life",
    "#% increased Projectile Speed",
    "#% increased Elemental Damage",
    "# to Level of all Spell Skills",
    "#% increased Quantity of Items found in this Area",
    "#% increased Pack size",
    "Grants # Life per Enemy Hit",
    "#% of Damage taken Recouped as Life",
    "#% increased Spirit",
    "Gain #% of Damage as Extra Lightning Damage",
    "#% increased Critical Damage Bonus for Attack Damage",
    "Gain #% of Damage as Extra Cold Damage",
    "Causes #% increased Stun Buildup",
    "#% increased Stun Duration",
    "Minions have #% increased maximum Life",
    "#% increased Energy Shield Recharge Rate",
    "Gain #% of Damage as Extra Fire Damage",
    "#% increased Magic Pack Size",
    "#% increased Charm Effect Duration",
    "#% increased Critical Hit Chance for Attacks",
    "#% increased Block chance",
    "#% increased Flask Life Recovery rate",
    "#% increased Flask Mana Recovery rate",
    "#% increased Flask Charges gained",
    "#% increased Freeze Buildup",
    "#% increased chance to Shock",
    "Minions deal #% increased Damage",
    "#% increased Experience gain",
    "#% increased Projectile Damage",
    "#% increased Damage with Bow Skills",
    "#% increased Attack Damage",
    "# to Level of all Lightning Spell Skills",
    "#% faster start of Energy Shield Recharge",
    "#% increased number of Monster Packs",
    "#% reduced Ignite Duration on you",
    "#% increased Stun Threshold",
    "#% increased Accuracy Rating",
    "#% of Damage taken Recouped as Mana",
    "#% increased Bleeding Duration on you",
    "#% increased Life Regeneration rate",
    "#% increased Charm Charges gained",
    "#% increased Stun Buildup",
    "#% increased amount of Life Leeched",
    "#% reduced Flask Charges used",
    "# to Level of all Fire Spell Skills",
    "#% increased Global Physical Damage",
    "Damage Penetrates #% Cold Resistance",
    "#% increased Poison Duration on you",
    "#% increased Damage with Bows",
    "#% increased Melee Damage",
    "#% increased Magnitude of Ignite you inflict",
    "Damage Penetrates #% Lightning Resistance",
    "#% increased Damage with Crossbows",
    "#% chance to inflict Bleeding on Hit",
    "Recover #% of Life on Kill",
    "#% increased Charges",
    "Monsters have #% increased Ailment Threshold",
    "#% increased maximum Mana",
    "#% increased Charges gained",
    "Gain # Rage on Melee Hit",
    "Monsters have #% increased Stun Threshold",
    "#% increased Charges per use",
    "#% to Monster Critical Damage Bonus",
    "#% increased Block chance",
    "#% reduced Chill Duration on you",
    "+#% Monster Elemental Resistances",
    "Players are Cursed with Enfeeble",
    "#% increased amount of Rare Chests",
    "Monsters deal #% of Damage as Extra Fire",
    "#% reduced Freeze Duration on you",
    "Allies in your Presence deal #% increased Damage",
    "#% increased Area of Effect",
    "#% increased Warcry Speed",
    "#% increased Monster Damage",
    "Monsters deal #% of Damage as Extra Cold",
    "#% reduced Shock duration on you",
    "#% increased Attack Speed with Bows",
    "#% increased Damage with Quarterstaves",
    "#% increased Monster Cast Speed",
    "#% more Monster Life",
    "# Charm Slot",
    "Allies in your Presence have # to Accuracy Rating",
    "Minions have #% to all Elemental Resistances",
    "#% increased Magnitude of Poison you inflict",
    "Players are Cursed with Elemental Weakness",
    "#% increased Monster Movement Speed",
    "#% increased Amount Recovered",
    "#% chance to Pierce an Enemy",
    "#% increased amount of Magic Chests",
    "#% increased Shock Duration",
    "Minions have #% increased Attack and Cast Speed",
    "#% reduced Charm Charges used",
    "# to Level of all Cold Spell Skills",
    "#% increased Attack Speed with Crossbows",
    "#% increased Life Recovery from Flasks",
    "Gain #% of maximum Energy Shield as additional Stun Threshold",
    "Monsters have #% increased Critical Hit Chance",
    "Players are Cursed with Temporal Chains",
    "#% chance to Poison on Hit",
    "#% increased maximum Life",
    "Monsters deal #% of Damage as Extra Lightning",
    "Allies in your Presence Regenerate # Life per second",
    "#% increased Spell Physical Damage",
    "Gain # Life per Enemy Hit with Attacks",
    "#% increased Totem Placement speed",
    "#% increased Skill Effect Duration",
    "#% increased Totem Damage",
    "Monster Damage Penetrates #% Elemental Resistances",
    "#% increased Elemental Ailment Threshold",
    "Area has patches of Burning Ground",
    "Monsters have #% increased Ignite Chance",
    "Gain # Rage when Hit by an Enemy",
    "Monsters have #% increased Stun Buildup",
    "#% increased amount of Mana Leeched",
    "Gains # Charges per Second",
    "Damage Penetrates #% Fire Resistance",
    "Monsters have #% chance to Poison on Hit",
    "#% increased Warcry Cooldown Recovery Rate",
    "Monsters have #% increased Freeze Buildup",
    "#% increased Totem Life",
    "Players gain #% reduced Flask Charges",
    "Monsters are Evasive",
    "Players have #% less Recovery Rate of Life and Energy Shield",
    "Monsters have #% chance to Bleed on Hit",
    "#% increased Damage with Maces",
    "#% increased Duration of Damaging Ailments on Enemies",
    "Monsters have #% increased Shock Chance",
    "#% increased Defences from Equipped Shield",
    "Triggered Spells deal #% increased Spell Damage",
    "Area has patches of Shocked Ground",
    "#% increased Weapon Swap Speed",
    "Monsters take #% reduced Extra Damage from Critical Hits",
    "#% increased Knockback Distance",
    "#% increased Energy Shield from Equipped Focus",
    "#% increased Magnitude of Bleeding you inflict",
    "#% increased Monster Attack Speed",
    "Monsters are Armoured",
    "#% increased Attack Speed with Quarterstaves",
    "Minions have #% additional Physical Damage Reduction",
    "#% increased Mana Recovery from Flasks",
    "# to Level of all Chaos Spell Skills",
    "#% increased Stun Buildup with Maces",
    "#% increased Flask Effect Duration",
    "Area has patches of Chilled Ground",
    "#% Chance to gain a Charge when you Kill an Enemy",
    "#% increased Damage with Hits against Rare and Unique Enemies",
    "#% increased Magnitude of Damaging Ailments you inflict with Critical Hits",
    "Monsters gain #% of Maximum Life as Extra Maximum Energy Shield",
    "Herald Skills deal #% increased Damage",
    "#% increased Area of Effect of Curses",
    "Offerings have #% increased Maximum Life",
    "#% maximum Player Resistances",
    "Allies in your Presence deal # to # additional Attack Lightning Damage",
    "#% increased amount of Chests",
    "Allies in your Presence deal # to # additional Attack Cold Damage",
    "Allies in your Presence deal # to # additional Attack Fire Damage",
    "#% increased Magnitude of Ailments you inflict",
    "#% increased Minion Accuracy Rating",
    "#% increased Accuracy Rating with Bows",
    "Allies in your Presence have #% increased Attack Speed",
    "# to Level of all Physical Spell Skills",
    "Allies in your Presence deal # to # additional Attack Physical Damage",
    "#% increased bonuses gained from Equipped Quiver",
    "#% increased Damage while you have an active Charm",
    "#% increased Chill Duration on Enemies",
    "#% increased Duration",
    "Minions have #% increased Critical Damage Bonus",
    "#% increased Magnitude of Shock you inflict",
    "#% increased Intelligence",
    "Minions have #% increased Critical Hit Chance",
    "Allies in your Presence have #% increased Critical Hit Chance",
    "Meta Skills gain #% increased Energy",
    "Recover #% of Mana on Kill",
    "Recover # Life when Used",
    "#% increased Curse Duration",
    "Allies in your Presence have #% increased Cast Speed",
    "Recover # Mana when Used",
    "#% increased Skill Speed",
    "#% increased Recovery rate",
    "Allies in your Presence have #% increased Critical Damage Bonus",
    "Allies in your Presence have #% to all Elemental Resistances",
    "Monsters deal #% of Damage as Extra Chaos",
    "#% increased Strength",
    "#% increased Dexterity",
    "#% increased Freeze Threshold",
    "Area has #% chance to contain a Strongbox",
    "#% increased chance to inflict Ailments",
    "#% to Maximum Lightning Resistance",
    "#% increased Crossbow Reload Speed",
    "Players have #% more Cooldown Recovery Rate",
    "#% less effect of Curses on Monsters",
    "Monsters have #% increased Accuracy Rating",
    "Area has #% chance to contain an Essence",
    "Empowered Attacks deal #% increased Damage",
    "#% increased Damage with Warcries",
    "Monsters fire # additional Projectiles",
    "#% to Maximum Fire Resistance",
    "Monsters Break Armour equal to #% of Physical Damage dealt",
    "Rare Monsters have a #% chance to have an additional Modifier",
    "Area has #% chance to contain a Shrine",
    "Mark Skills have #% increased Cast Speed",
    "#% increased Thorns damage",
    "#% increased Pin Buildup",
    "Enemies Chilled by your Hits can be Shattered as though Frozen",
    "#% increased Poison Duration",
    "#% increased Freeze Buildup with Quarterstaves",
    "#% increased Daze Buildup",
    "Break #% increased Armour",
    "#% increased Stun Threshold if you haven't been Stunned Recently",
    "#% increased Attack Speed per 5 Dexterity",
    "Monsters have #% increased Area of Effect",
    "Mark Skills have #% increased Skill Effect Duration",
    "Debuffs on you expire #% faster",
    "#% increased Damage against Enemies with Fully Broken Armour",
    "#% increased Duration of Ignite, Shock and Chill on Enemies",
    "#% chance to Blind Enemies on Hit with Attacks",
    "Attacks Gain #% of Damage as Extra Fire Damage",
    "Projectiles Pierce all Ignited enemies",
    "Area contains # additional packs of Vaal Monsters",
    "Monsters have #% chance to steal Power, Frenzy and Endurance charges on Hit",
    "Area contains # additional packs of Beasts",
    "#% of Recovery applied Instantly",
    "Gain # Guard during Effect",
    "Area contains # additional packs of Undead",
    "Area contains # additional packs of Bramble Monsters",
    "Area contains # additional packs of Ezomyte Monsters",
    "#% increased Weapon Damage per 5 Strength",
    "#% increased Slowing Potency of Debuffs on You",
    "Area contains # additional packs of Transcended Monsters",
    "Leeches #% of maximum Life when you Cast a Spell",
    "#% increased Bleeding Duration",
    "Area contains # additional packs of Iron Guards",
    "#% increased Attack and Cast Speed",
    "Breaches have #% increased Monster density",
    "Area contains # additional packs of Faridun Monsters",
    "#% to Maximum Cold Resistance",
    "Trigger Ember Fusillade Skill on casting a Spell",
    "#% increased Area of Effect for Attacks per 5 Intelligence",
    "#% additional Physical Damage Reduction",
    "Area contains an additional Shrine",
    "Fire Damage from Hits Contributes to Shock Chance instead of Ignite Chance and Magnitude",
    "Rare Monsters have # additional Modifier",
    "Lightning Damage from Hits Contributes to Freeze Buildup instead of Shock Chance",
    "Cold Damage from Hits Contributes to Ignite Chance and Magnitude instead of Chill Magnitude",
    "Gain #% of Damage as Chaos Damage per Undead Minion",
    "#% of Maximum Life Converted to Energy Shield",
    "#% of Damage taken bypasses Energy Shield",
    "Gain #% of Maximum Life as Extra Maximum Energy Shield",
    "#% chance to not destroy Corpses when Consuming Corpses",
    "#% increased Presence Area of Effect",
    "Area contains # additional packs of Plagued Monsters",
    "Lightning damage from Hits Contributes to Electrocution Buildup",
    "Breaches in Area contain # additional Clasped Hand",
    "Trigger Spark Skill on killing a Shocked Enemy",
    "#% increased Cooldown Recovery Rate",
    "Area contains an additional Essence",
    "Minions Revive #% faster",
    "#% increased Quantity of Breach Splinters dropped by Breach Monsters in Area",
    "#% of Spell Mana Cost Converted to Life Cost",
    "Bow Attacks fire # additional Arrows",
    "Area contains an additional Strongbox",
    "#% increased Armour, Evasion and Energy Shield",
    "When a Party Member in your Presence Casts a Spell, you",
    "Areas which contain Breaches have #% chance to contain an additional Breach",
    "#% increased Life Recovered",
    "#% of Cold Damage Converted to Lightning Damage",
    "#% of Skill Mana Costs Converted to Life Costs",
    "Removes #% of Life Recovered from Mana when used",
    "#% increased Magnitude of Chill you inflict",
    "Intelligence provides no inherent bonus to Maximum Mana",
    "Projectiles Split towards # targets",
    "Attacks Chain an additional time",
    "#% increased Damage",
    "Maim on Critical Hit",
    "Enemies in your Presence are Ignited as though dealt # Base Fire Damage",
    "Share Charges with Allies in your Presence",
    "#% of Fire Damage Converted to Cold Damage",
    "#% increased Chance to be afflicted by Ailments when Hit",
    "#% increased Movement Speed while affected by an Ailment",
    "#% reduced Mana Cost of Skills",
    "#% of Elemental Damage Converted to Fire Damage",
    "#% of Elemental Damage Converted to Lightning Damage",
    "#% of Elemental Damage Converted to Cold Damage",
    "Gain #% of Maximum Mana as Extra Maximum Energy Shield",
    "#% increased Rarity of Items found when on Low Life",
    "Mana Flasks gain # charges per Second",
    "#% increased Mana Recovered",
    "#% increased Effect of Auras from your Aura Skills",
    "Gain #% of Damage as Extra Chaos Damage",
    "Critical Hits Ignore Enemy Monster Lightning Resistance",
    "#% increased Reload Speed",
    "Trigger Decompose Skill on Step",
    "Physical Damage is Pinning",
    "#% increased Damage if you have Consumed a Corpse Recently",
    "Causes Bleeding on Hit",
    "#% chance to not consume a bolt if you've Reloaded Recently",
    "Causes Daze buildup equal to #% of Damage dealt",
    "Upgrades Radius to Medium",
    "Trigger Greater Lightning Bolt Skill on Critical Hit",
    "#% increased Armour Break Duration",
    "#% increased Global Defences",
    "Minions gain #% of their Maximum Life as Extra Maximum Energy Shield",
    "Minions have #% to Chaos Resistance",
    "You have no Life Regeneration",
    "# Intelligence Requirement",
    "#% of Physical Damage taken as Fire Damage",
    "Increases and Reductions to Minion Damage also affect you",
    "Causes Double Stun Buildup",
    "#% increased Attack Speed while on Full Mana",
    "Gain 0% to #% increased Movement Speed at random when Hit, until Hit again",
    "#% to Block chance",
    "Sacrifice #% of Life to gain that much Energy Shield when you Cast a Spell",
    "#% increased Effect of Withered",
    "#% more Recovery if used while on Low Life",
    "#% of Lightning Damage Converted to Cold Damage",
    "#% more Recovery if used while on Low Mana",
    "#% increased Effect of your Curses",
    "#% of your Life Regeneration is granted to Allies in your Presence",
    "Grants #% of Life Recovery to Minions",
    "# Physical damage taken from Projectile Attacks",
    "#% chance for Energy Shield Recharge to start when you Kill an Enemy",
    "All Damage from Hits with this Weapon Contributes to Freeze Buildup",
    "Drop Ignited Ground while moving, which lasts 8 seconds and Ignites as though dealing Fire Damage equal to #% of your maximum Life",
    "#% increased Effect of your Mark Skills",
    "Culling Strike against Frozen Enemies",
    "Strength can satisfy other Attribute Requirements of Melee Weapons and Melee Skills",
    "Always deals Critical Hits against Heavy Stunned Enemies",
    "Eldritch Battery",
    "You have a Smoke Cloud around you while stationary",
    "Gain # Rage when Critically Hit by an Enemy",
    "#% increased Stun Recovery",
    "# to # Fire Thorns damage",
    "Removes #% of Mana Recovered from Life when used",
    "Enemies are Culled on Block",
    "You take #% of damage from Blocked Hits",
    "#% increased Spell Damage per 10 Spirit",
    "Hits Break # Armour",
    "Life Flasks gain # charges per Second",
    "Iron Reflexes",
    "Minions' Resistances are equal to yours",
    "Lose # Life when you use a Skill",
    "Apply Fire Exposure when fully breaking enemy Armour",
    "Pain Attunement",
    "Unwavering Stance",
    "Curses you inflict are reflected back to you",
    "You cannot be Ignited for # second after being Ignited",
    "You cannot be Shocked for # second after being Shocked",
    "#% chance to be inflicted with Bleeding when Hit",
    "#% increased Blind Effect",
    "Base Critical Hit Chance for Attacks with Weapons is #%",
    "You cannot be Frozen for # second after being Frozen",
    "No Movement Speed Penalty while Shield is Raised",
    "#% chance to Avoid Death from Hits",
    "Mana Flasks used while on Low Mana apply Recovery Instantly",
    "Corpses in your Presence Explode when you Warcry,",
    "# to Maximum Rage",
    "Warcry Skills have #% increased Area of Effect",
    "You cannot be Chilled for # second after being Chilled",
    "You count as on Full Mana while at #% of maximum Mana or above",
    "Life Flasks used while on Low Life apply Recovery Instantly",
    "#% of Melee Physical Damage taken reflected to Attacker",
    "Projectiles have #% chance for an additional Projectile when Forking",
    "#% increased Evasion Rating when on Full Life",
    "Every 3 seconds, Consume a nearby Corpse to Recover #% of Life",
    "Your speed is unaffected by Slows",
    "Enemies in your Presence have Fire Exposure",
    "#% increased Movement Speed when on Full Life",
    "#% increased Mana Regeneration Rate while stationary",
    "Energy Shield Recharge is not interrupted by Damage if Recharge began Recently",
    "#% increased Mana Regeneration Rate per Fragile Regrowth",
    "Breaches in Area spawn #% increased Magic Monsters",
    "Gain # Fragile Regrowth each second",
    "Maximum # Fragile Regrowth",
    "#% faster Curse Activation",
    "Lose all Power Charges on reaching maximum Power Charges",
    "#% chance to gain a Power Charge on Hit",
    "Freeze as though dealing Cold damage equal to #% of your maximum Mana when Hit",
    "Lose all Fragile Regrowth when Hit",
    "Deal #% increased Damage with Hits to Rare or Unique Enemies for each second they've ever been in your Presence, up to a maximum of 200%",
    "#% of Life Regenerated per second per Fragile Regrowth",
    "#% of Physical Damage prevented Recouped as Life",
    "Projectiles have #% chance to Chain an additional time from terrain",
    "Iron Will",
    "#% of Fire Damage from Hits taken as Physical Damage",
    "#% less Damage taken if you have not been Hit Recently",
    "Areas which contain Breaches have #% chance to contain three additional Breaches",
    "Blind Chilled enemies on Hit",
    "#% increased Evasion Rating if you have been Hit Recently",
    "Double Stun Threshold while Shield is Raised",
    "Breaches in Area spawn an additional Rare Monster",
    "Shocks you when you reach maximum Power Charges",
    "Offering Skills have #% increased Duration",
    "Regenerate #% of Life per second while on Low Life",
    "#% reduced Effect of Chill on you",
    "#% of Damage is taken from Mana before Life",
    "Damage over Time bypasses your Energy Shield",
    "Recover #% of Life for each Endurance Charge consumed",
    "#% reduced effect of Shock on you",
    "#% to Thorns Critical Hit Chance",
    "#% reduced effect of Ignite on you",
    "Damaging Ailments deal damage #% faster",
    "Iron Grip",
    "Every Rage also grants #% increased Armour",
    "Critical Hits Poison the enemy",
    "#% chance to Aggravate Bleeding on targets you Critically Hit with Attacks",
    "#% to Fire Resistance while on Low Life",
    "Bleeding you inflict is Aggravated",
    "Every Rage also grants #% increased Stun Threshold",
    "Regenerate #% of Life per second",
    "Damage Blocked is Recouped as Mana",
    "#% increased Warcry Buff Effect",
    "When you Leech Life from a Hit, Allies in your Presence also Leech the same amount of Life",
    "#% increased Endurance Charge Duration",
    "#% chance for Flasks you use to not consume Charges",
    "Charms gain # charges per Second",
    "You count as on Low Life while at #% of maximum Life or below",
    "Recover #% of Mana on Kill",
    "#% increased Mana Flask Charges gained",
    "#% increased Life and Mana Recovery from Flasks",
    "Thorns damage is triggered by all Hits",
    "Delirious Monsters Killed in Area provide #% increased Reward Progress",
    "#% increased Stack size of Simulacrum Splinters found in Area",
    "#% increased Life Flask Charges gained",
    "Permanently Intimidate enemies on Block",
    "Delirium Encounters in Area are #% more likely to spawn Unique Bosses"
];